version: 0.2

phases:
  build:
    commands:
      - mkdir -p build
      - cp appspec.yml build/
      - cp -r scripts/ build/
      - cp index.html build/
artifacts:
  files:
    - '**/*'
  base-directory: build
